# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
  - task: Gradle@3
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      publishJUnitResults: false
      tasks: 'assembleMagiskDebug assembleMagiskRelease'

  - task: CopyFiles@2
    inputs: 
      contents: '**/build/outputs/magisk/dreamland-**.zip'
      targetFolder: '$(build.artifactStagingDirectory)'
      cleanTargetFolder: true
      flattenFolders: true

  - task: CopyFiles@2
    inputs:
      contents: '**/build/outputs/mapping/release/**.txt'
      targetFolder: '$(build.artifactStagingDirectory)'
      cleanTargetFolder: false
      flattenFolders: true
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'dreamland-$(build.buildId).zip'
      artifactType: 'container'

pr: none
